apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: affine
  description: Affine document collaboration tool
  tags:
    - devops
    - docs
spec:
  type: service
  lifecycle: production
  owner: user:guest
